# Generated by Django 4.1.12 on 2023-10-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance',
            field=models.IntegerField(default=100),
        ),
    ]
